// Test case that compares a file generated by polars_excel_writer with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;

use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;
use rust_xlsxwriter::XlsxError;

// Compare output against target Excel file using PolarsExcelWriter.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2, 2, 2],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    excel_writer.set_worksheet_name("Data")?;
    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Get the current worksheet and set the name that way.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2, 2, 2],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();

    let worksheet = excel_writer.worksheet()?;
    worksheet.set_name("Data")?;

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

#[test]
fn dataframe_write_excel06_1() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe06")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_write_excel06_2() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe06")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
