// Test case that compares a file generated by polars_excel_writer with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;

use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;
use rust_xlsxwriter::XlsxError;

// Compare output against target Excel file using PolarsExcelWriter.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2, 2, 2],
    )?;

    let format = rust_xlsxwriter::Format::new().set_font_color("#FF0000");

    let mut excel_writer = PolarsExcelWriter::new();
    excel_writer.set_header_format(&format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

#[test]
fn dataframe_excelwriter20() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe20")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .ignore_file("xl/styles.xml")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
