// Test case that compares a file generated by polars_excel_writer with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2023, John McNamara, jmcnamara@cpan.org

use crate::common;

use polars::prelude::*;
use polars_excel_writer::{ExcelWriter, PolarsXlsxWriter};
use rust_xlsxwriter::XlsxError;

// Test case to compare dataframe output against an Excel file.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2, 2, 2],
    )
    .unwrap();

    let mut file = std::fs::File::create(filename).unwrap();

    ExcelWriter::new(&mut file).finish(&mut df).unwrap();

    Ok(())
}

// Test case to compare dataframe output against an Excel file.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2, 2, 2],
    )
    .unwrap();

    let mut xl = PolarsXlsxWriter::new();
    xl.write_dataframe(&df).unwrap();
    xl.write_excel(filename).unwrap();

    Ok(())
}

#[test]
fn dataframe_excelwriter01() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe01")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_write_excel01() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe01")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
