// Test case that compares a file generated by polars_excel_writer with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;

use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;
use rust_xlsxwriter::{Format, XlsxError};

// Compare output against target Excel file using PolarsExcelWriter. This file
// has bold integers in the first column.

// Use dtype formatting.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    let format = Format::new().set_num_format("0.0000");

    excel_writer.set_dtype_format(DataType::Float64, format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Ensure column formatting overrides dtype formatting.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    let format = Format::new().set_num_format("0.0000");

    excel_writer.set_dtype_format(DataType::Float64, &format);
    excel_writer.set_column_format("Bar", &format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Use column formatting.
fn create_new_xlsx_file_3(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    let format = Format::new().set_num_format("0.0000");

    excel_writer.set_column_format("Bar", format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Use all float dtype formatting.
fn create_new_xlsx_file_4(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    let format = Format::new().set_num_format("0.0000");

    excel_writer.set_dtype_float_format(format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Use all number dtype formatting.
fn create_new_xlsx_file_5(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    let num_format = Format::new().set_num_format("0.0000");
    let default_format = Format::new();

    excel_writer.set_dtype_number_format(num_format);

    // Override the number format for the "Foo" column.
    excel_writer.set_column_format("Foo", default_format);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

// Use number precision option.
fn create_new_xlsx_file_6(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &[2.4, 2.4, 2.4],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();
    excel_writer.set_float_precision(4);

    excel_writer.write_dataframe(&df)?;
    excel_writer.save(filename)?;

    Ok(())
}

#[test]
fn dataframe_excelwriter14_1() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_excelwriter14_2() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_excelwriter14_3() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_3)
        .unique("3")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_excelwriter14_4() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_4)
        .unique("4")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_excelwriter14_5() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_5)
        .unique("5")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn dataframe_excelwriter14_6() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe14")
        .set_function(create_new_xlsx_file_6)
        .unique("6")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
