// Test case that compares a file generated by polars_excel_writer with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2026, John McNamara, jmcnamara@cpan.org

use crate::common;

use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;
use rust_xlsxwriter::XlsxError;

// Compare output against target Excel file using PolarsExcelWriter.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let df: DataFrame = df!(
        "Foo" => &[1, 1, 1],
        "Bar" => &["https://pola.rs/", "https://pola.rs/", "https://pola.rs/"],
    )?;

    let mut excel_writer = PolarsExcelWriter::new();

    excel_writer.enable_column_urls("Bar");

    excel_writer.set_autofit(true);

    excel_writer.write_dataframe(&df)?;

    excel_writer.save(filename)?;

    Ok(())
}

#[test]
fn dataframe_write_excel21() {
    let test_runner = common::TestRunner::new()
        .set_name("dataframe21")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
